services:
  marble_api:
    image: marbleclimate/marble-api:latest
    environment:
      - MARBLE_API_MONGODB_URI=mongodb://mongo:27017
    ports:
      - 8000:8000
  mongo:
    # percona is used instead of mongodb community image because it supports encryption at rest
    # versions > 8.0.4 are currently incompatible with recent malloc fix from linux kernels > 6.19
    image: percona/percona-server-mongodb:8.0.4

